### ISSUE TITLE
サーバーへデプロイ後、音楽を再生しようとすると Status code: 429 エラーが発生する

### ISSUE THREAD

**Issue by dashimaki929** [dashimaki929/discord-jukebox#2]
$ npm run start
> Ready!

`!summon`

```
MinigetError: input stream: Status code: 429
    at ClientRequest.<anonymous> (/root/DiscordBot/discord-jukebox/node_modules/miniget/dist/index.js:190:31)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:640:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at TLSSocket.Readable.push (_stream_readable.js:218:10) {
  statusCode: 429
}
```

**Comment by dashimaki929** [comment]
https://github.com/fent/node-ytdl-core/issues/444#issuecomment-670341951

上記対応で Cookie を設定すればいけそう
